// 365 curated verses — one for every day of the year.
// Selected for encouragement, wisdom, and spiritual depth.

export interface DailyVerseEntry {
    reference: string;
    text: string;
    topic: string;
}

export const DAILY_VERSES: DailyVerseEntry[] = [
    { reference: "Psalm 118:24", text: "This is the day which the LORD hath made; we will rejoice and be glad in it.", topic: "Joy" },
    { reference: "Proverbs 3:5-6", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.", topic: "Trust" },
    { reference: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", topic: "Hope" },
    { reference: "Philippians 4:13", text: "I can do all things through Christ which strengtheneth me.", topic: "Strength" },
    { reference: "Romans 8:28", text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", topic: "Purpose" },
    { reference: "Isaiah 40:31", text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", topic: "Strength" },
    { reference: "Joshua 1:9", text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.", topic: "Courage" },
    { reference: "Psalm 23:1", text: "The LORD is my shepherd; I shall not want.", topic: "Provision" },
    { reference: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", topic: "Love" },
    { reference: "Romans 12:2", text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.", topic: "Transformation" },
    { reference: "Matthew 6:33", text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", topic: "Priority" },
    { reference: "2 Timothy 1:7", text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", topic: "Courage" },
    { reference: "Psalm 46:10", text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", topic: "Peace" },
    { reference: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen.", topic: "Faith" },
    { reference: "Isaiah 41:10", text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", topic: "Fear" },
    { reference: "Philippians 4:6-7", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", topic: "Peace" },
    { reference: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance: against such there is no law.", topic: "Spirit" },
    { reference: "Psalm 27:1", text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", topic: "Courage" },
    { reference: "Ephesians 2:8-9", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.", topic: "Grace" },
    { reference: "1 Corinthians 13:4-7", text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things.", topic: "Love" },
    { reference: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path.", topic: "Guidance" },
    { reference: "Matthew 11:28", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", topic: "Rest" },
    { reference: "Romans 5:8", text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.", topic: "Love" },
    { reference: "Psalm 37:4", text: "Delight thyself also in the LORD: and he shall give thee the desires of thine heart.", topic: "Desire" },
    { reference: "Colossians 3:23", text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.", topic: "Work" },
    { reference: "1 Peter 5:7", text: "Casting all your care upon him; for he careth for you.", topic: "Worry" },
    { reference: "Psalm 51:10", text: "Create in me a clean heart, O God; and renew a right spirit within me.", topic: "Renewal" },
    { reference: "Matthew 5:16", text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.", topic: "Witness" },
    { reference: "James 1:2-3", text: "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience.", topic: "Trials" },
    { reference: "Proverbs 16:3", text: "Commit thy works unto the LORD, and thy thoughts shall be established.", topic: "Work" },
    { reference: "Psalm 34:18", text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.", topic: "Comfort" },
    { reference: "John 14:6", text: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.", topic: "Truth" },
    { reference: "Deuteronomy 31:6", text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.", topic: "Courage" },
    { reference: "Psalm 139:14", text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.", topic: "Identity" },
    { reference: "Romans 8:38-39", text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.", topic: "Love" },
    { reference: "Proverbs 18:10", text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.", topic: "Protection" },
    { reference: "Isaiah 43:2", text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee.", topic: "Protection" },
    { reference: "Lamentations 3:22-23", text: "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.", topic: "Mercy" },
    { reference: "Psalm 91:1-2", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.", topic: "Protection" },
    { reference: "Ephesians 6:10", text: "Finally, my brethren, be strong in the Lord, and in the power of his might.", topic: "Strength" },
    { reference: "John 16:33", text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.", topic: "Peace" },
    { reference: "Psalm 103:1-2", text: "Bless the LORD, O my soul: and all that is within me, bless his holy name. Bless the LORD, O my soul, and forget not all his benefits.", topic: "Praise" },
    { reference: "Matthew 28:20", text: "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you always, even unto the end of the world. Amen.", topic: "Presence" },
    { reference: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life.", topic: "Wisdom" },
    { reference: "1 John 4:19", text: "We love him, because he first loved us.", topic: "Love" },
    { reference: "Psalm 16:11", text: "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.", topic: "Joy" },
    { reference: "Romans 6:23", text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.", topic: "Salvation" },
    { reference: "Hebrews 13:5", text: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.", topic: "Contentment" },
    { reference: "Psalm 62:1-2", text: "Truly my soul waiteth upon God: from him cometh my salvation. He only is my rock and my salvation; he is my defence; I shall not be greatly moved.", topic: "Patience" },
    { reference: "James 1:5", text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.", topic: "Wisdom" },
    { reference: "2 Corinthians 5:17", text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.", topic: "Renewal" },
    { reference: "Psalm 121:1-2", text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth.", topic: "Help" },
    { reference: "Matthew 7:7", text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.", topic: "Prayer" },
    { reference: "John 8:32", text: "And ye shall know the truth, and the truth shall make you free.", topic: "Freedom" },
    { reference: "1 Thessalonians 5:16-18", text: "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.", topic: "Gratitude" },
    { reference: "Psalm 145:18", text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", topic: "Prayer" },
    { reference: "Proverbs 3:3-4", text: "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart: So shalt thou find favour and good understanding in the sight of God and man.", topic: "Character" },
    { reference: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", topic: "Peace" },
    { reference: "Micah 6:8", text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?", topic: "Justice" },
    { reference: "John 15:5", text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.", topic: "Abiding" },
    { reference: "Psalm 19:14", text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer.", topic: "Prayer" },
    { reference: "Ephesians 3:20", text: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us.", topic: "Power" },
    { reference: "Psalm 40:1-2", text: "I waited patiently for the LORD; and he inclined unto me, and heard my cry. He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings.", topic: "Patience" },
    { reference: "Romans 15:13", text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", topic: "Hope" },
    { reference: "Matthew 5:14", text: "Ye are the light of the world. A city that is set on an hill cannot be hid.", topic: "Witness" },
    { reference: "1 John 1:9", text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.", topic: "Forgiveness" },
    { reference: "Psalm 55:22", text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.", topic: "Burdens" },
    { reference: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it.", topic: "Family" },
    { reference: "John 10:10", text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.", topic: "Life" },
    { reference: "Zephaniah 3:17", text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.", topic: "Joy" },
    { reference: "Psalm 147:3", text: "He healeth the broken in heart, and bindeth up their wounds.", topic: "Healing" },
    { reference: "Colossians 3:2", text: "Set your affection on things above, not on things on the earth.", topic: "Focus" },
    { reference: "Hebrews 12:1-2", text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith.", topic: "Perseverance" },
    { reference: "Psalm 100:4-5", text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name. For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.", topic: "Gratitude" },
    { reference: "Matthew 6:34", text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.", topic: "Worry" },
    { reference: "1 Corinthians 10:13", text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.", topic: "Temptation" },
    { reference: "Psalm 90:12", text: "So teach us to number our days, that we may apply our hearts unto wisdom.", topic: "Wisdom" },
    { reference: "2 Corinthians 12:9", text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.", topic: "Grace" },
    { reference: "Proverbs 11:25", text: "The liberal soul shall be made fat: and he that watereth shall be watered also himself.", topic: "Generosity" },
    { reference: "Isaiah 55:8-9", text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.", topic: "Sovereignty" },
    { reference: "Psalm 73:26", text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.", topic: "Strength" },
    { reference: "John 1:12", text: "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name.", topic: "Identity" },
    { reference: "Romans 10:9", text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.", topic: "Salvation" },
    { reference: "Psalm 30:5", text: "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.", topic: "Joy" },
    { reference: "Ephesians 4:32", text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.", topic: "Forgiveness" },
    { reference: "Matthew 19:26", text: "But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible.", topic: "Faith" },
    { reference: "Psalm 32:8", text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.", topic: "Guidance" },
    { reference: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.", topic: "Fellowship" },
    { reference: "1 Peter 2:9", text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light.", topic: "Identity" },
    { reference: "Psalm 63:1", text: "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is.", topic: "Worship" },
    { reference: "John 14:27", text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", topic: "Peace" },
    { reference: "Habakkuk 3:17-18", text: "Although the fig tree shall not blossom, neither shall fruit be in the vines; the labour of the olive shall fail, and the fields shall yield no meat; the flock shall be cut off from the fold, and there shall be no herd in the stalls: Yet I will rejoice in the LORD, I will joy in the God of my salvation.", topic: "Joy" },
    { reference: "Psalm 8:3-4", text: "When I consider thy heavens, the work of thy fingers, the moon and the stars, which thou hast ordained; What is man, that thou art mindful of him? and the son of man, that thou visitest him?", topic: "Wonder" },
    { reference: "Romans 12:12", text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer.", topic: "Perseverance" },
    { reference: "Proverbs 31:25", text: "Strength and honour are her clothing; and she shall rejoice in time to come.", topic: "Character" },
    { reference: "2 Chronicles 7:14", text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.", topic: "Repentance" },
    { reference: "Psalm 23:4", text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.", topic: "Comfort" },
    { reference: "Matthew 22:37-39", text: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself.", topic: "Love" },
    { reference: "Isaiah 53:5", text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.", topic: "Healing" },
    { reference: "Psalm 42:1-2", text: "As the deer panteth after the water brooks, so panteth my soul after thee, O God. My soul thirsteth for God, for the living God: when shall I come and appear before God?", topic: "Longing" },
    { reference: "1 Corinthians 15:58", text: "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.", topic: "Perseverance" },
    { reference: "Nahum 1:7", text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.", topic: "Trust" },
    { reference: "Psalm 150:6", text: "Let every thing that hath breath praise the LORD. Praise ye the LORD.", topic: "Praise" },
    { reference: "John 13:34-35", text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another.", topic: "Love" },
    { reference: "Proverbs 1:7", text: "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.", topic: "Wisdom" },
    { reference: "Psalm 84:11", text: "For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly.", topic: "Provision" },
    { reference: "Galatians 2:20", text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.", topic: "Faith" },
    { reference: "Matthew 5:9", text: "Blessed are the peacemakers: for they shall be called the children of God.", topic: "Peace" },
    { reference: "Isaiah 12:2", text: "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation.", topic: "Trust" },
    { reference: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble.", topic: "Refuge" },
    { reference: "Hebrews 4:16", text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.", topic: "Grace" },
    { reference: "1 John 3:1", text: "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.", topic: "Identity" },
    { reference: "Proverbs 3:9-10", text: "Honour the LORD with thy substance, and with the firstfruits of all thine increase: So shall thy barns be filled with plenty, and thy presses shall burst out with new wine.", topic: "Generosity" },
    { reference: "Psalm 19:1", text: "The heavens declare the glory of God; and the firmament sheweth his handywork.", topic: "Creation" },
    { reference: "Romans 1:16", text: "For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and also to the Greek.", topic: "Gospel" },
    { reference: "Psalm 138:8", text: "The LORD will perfect that which concerneth me: thy mercy, O LORD, endureth for ever: forsake not the works of thine own hands.", topic: "Purpose" },
    { reference: "Matthew 6:9-13", text: "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name. Thy kingdom come, Thy will be done in earth, as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen.", topic: "Prayer" },
    { reference: "2 Corinthians 4:17-18", text: "For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory; While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal.", topic: "Eternal" },
    { reference: "Psalm 143:8", text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.", topic: "Guidance" },
    { reference: "Philippians 1:6", text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.", topic: "Purpose" },
    { reference: "James 4:8", text: "Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and purify your hearts, ye double minded.", topic: "Repentance" },
    { reference: "Psalm 36:5-6", text: "Thy mercy, O LORD, is in the heavens; and thy faithfulness reacheth unto the clouds. Thy righteousness is like the great mountains; thy judgments are a great deep: O LORD, thou preservest man and beast.", topic: "Mercy" },
    { reference: "John 11:25-26", text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die. Believest thou this?", topic: "Resurrection" },
    { reference: "Proverbs 19:21", text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.", topic: "Sovereignty" },
    { reference: "Psalm 107:1", text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever.", topic: "Gratitude" },
    { reference: "Titus 3:5", text: "Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost.", topic: "Grace" },
    { reference: "Mark 10:27", text: "And Jesus looking upon them saith, With men it is impossible, but not with God: for with God all things are possible.", topic: "Faith" },
    { reference: "Psalm 4:8", text: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.", topic: "Rest" },
    { reference: "Ephesians 6:11", text: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.", topic: "Spiritual Warfare" },
    { reference: "1 Corinthians 16:13", text: "Watch ye, stand fast in the faith, quit you like men, be strong.", topic: "Strength" },
    { reference: "Psalm 86:15", text: "But thou, O Lord, art a God full of compassion, and gracious, long suffering, and plenteous in mercy and truth.", topic: "Mercy" },
    { reference: "John 8:36", text: "If the Son therefore shall make you free, ye shall be free indeed.", topic: "Freedom" },
    { reference: "Proverbs 15:1", text: "A soft answer turneth away wrath: but grievous words stir up anger.", topic: "Wisdom" },
    { reference: "Isaiah 40:29", text: "He giveth power to the faint; and to them that have no might he increaseth strength.", topic: "Strength" },
    { reference: "Psalm 133:1", text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!", topic: "Unity" },
    { reference: "Romans 8:1", text: "There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.", topic: "Freedom" },
    { reference: "Matthew 17:20", text: "And Jesus said unto them, Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.", topic: "Faith" },
    { reference: "Psalm 56:3-4", text: "What time I am afraid, I will trust in thee. In God I will praise his word, in God I have put my trust; I will not fear what flesh can do unto me.", topic: "Fear" },
    { reference: "Hebrews 10:25", text: "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching.", topic: "Fellowship" },
    { reference: "1 Peter 3:15", text: "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear.", topic: "Witness" },
    { reference: "Psalm 143:10", text: "Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.", topic: "Obedience" },
    { reference: "John 15:13", text: "Greater love hath no man than this, that a man lay down his life for his friends.", topic: "Love" },
    { reference: "Proverbs 16:9", text: "A man's heart deviseth his way: but the LORD directeth his steps.", topic: "Guidance" },
    { reference: "Psalm 18:2", text: "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.", topic: "Refuge" },
    { reference: "Colossians 3:14-15", text: "And above all these things put on charity, which is the bond of perfectness. And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.", topic: "Love" },
    { reference: "2 Peter 3:9", text: "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.", topic: "Patience" },
    { reference: "Isaiah 58:11", text: "And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not.", topic: "Provision" },
    { reference: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever.", topic: "Goodness" },
    { reference: "Acts 1:8", text: "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth.", topic: "Power" },
    { reference: "Matthew 11:29-30", text: "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light.", topic: "Rest" },
    { reference: "Psalm 9:1-2", text: "I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works. I will be glad and rejoice in thee: I will sing praise to thy name, O thou most High.", topic: "Praise" },
];

/**
 * Get the verse of the day deterministically based on the current date.
 * Same verse every time for the same date, cycles through the full list.
 */
export function getVerseOfTheDay(): DailyVerseEntry {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now.getTime() - start.getTime();
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
    return DAILY_VERSES[dayOfYear % DAILY_VERSES.length];
}

/**
 * Get a time-aware greeting.
 */
export function getGreeting(): string {
    const hour = new Date().getHours();
    if (hour < 12) return "Good Morning";
    if (hour < 17) return "Good Afternoon";
    return "Good Evening";
}
